FROM node:16.17.0-alpine3.16 as build
WORKDIR /usr/app
COPY ./bookroom-ui-react /usr/app
RUN npm install
RUN npm ci
RUN npm run build

FROM nginx:1.23.1-alpine
EXPOSE 80
COPY ./bookroom-ui-react/enginex.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/app/build /usr/share/nginx/html