version: '3.9'
services:
  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  #  container_name: rabbitmq
  #  ports:
  #      - 5672:5672
  #      - 15672:15672
  #  environment:
  #      - RABBITMQ_DEFAULT_USER=queryUpdate
  #      - RABBITMQ_DEFAULT_PASS=queryUpdate
  #  networks:
  #    book_room:
  #      ipv4_address: 10.5.0.4
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: bookRoomUser
      POSTGRES_PASSWORD: bookRoomSpecialPasswordk
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      book_room:
        ipv4_address: 10.5.0.2
  #mongo:
  #  image: mongo
  #  container_name: mongo    
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: Root!123
  #  ports:
  #    - "27017:27017"
  #  networks:
  #    book_room:
  #      ipv4_address: 10.5.0.3
networks:
  book_room:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1