version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-bookroom
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=bookRoomUser
        - RABBITMQ_DEFAULT_PASS=bookRoomSpecialPassword
    networks:
      book_room:
        ipv4_address: 10.5.0.4
  postgres:
    container_name: postgre-bookroom
    image: postgres
    environment:
      POSTGRES_USER: bookRoomUser
      POSTGRES_PASSWORD: bookRoomSpecialPassword
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      book_room:
        ipv4_address: 10.5.0.2
  mongo:
    image: mongo
    container_name: mongo-bookroom
    environment:
      MONGO_INITDB_ROOT_USERNAME: bookRoomUser
      MONGO_INITDB_ROOT_PASSWORD: bookRoomSpecialPassword
    ports:
      - "27017:27017"
    networks:
      book_room:
        ipv4_address: 10.5.0.3
networks:
  book_room:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1